arch: amd64
os: linux
dist: xenial

language: java
jdk: openjdk8

install:
  - ./.travis/install_examples.sh

script:
  - ./.travis/execute_tests.sh

after_success:
  - ./.travis/code_coverage.sh

branch:
  only:
    - master

notifications:
  email: false