name: deploy-snapshot

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup JDK8 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh-flacoco-snapshots
          server-username: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          server-password: ${{ secrest.OSSH_TOKEN_PASSWORD }}
      - name: Deploy to Snapshot repository
        run: mvn deploy -DskipTests