name: deploy-snapshot

on:
  push:
    branches:
      - master

jobs:
  deploy-snapshot:
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup JDK8 and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh-flacoco-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy to Snapshot repository
        run: mvn deploy --batch-mode -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
